title: The bets Cheese
author: Davey
email: realemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
cheese based facts

# social links
twitter_username: 
github_username:DaveyElf

show_excerpts: false
theme: minima
